services:
  mariadb:
    restart: always
    build:
      context: .
    network_mode: "host"
    volumes:
      - 'mariadb_data:/var/lib/mysql'
    env_file:
      - .env
volumes:
  mariadb_data:
    driver: local
